version: '3.4'

services:
  app:
    container_name: avitotech_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "banners_app.app:app"]
    ports:
      - 8000:8000

    env_file:
      - ./.env-non-dev

  db:
    container_name: avitotech_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres
    env_file:
      - ./.env-non-dev


  redis: 
    image: redis
    container_name: avitotech_redis