version: '3.4'

services:
  app:
    container_name: avitotech_app
    build: ./
    depends_on:
      - db
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "banners_app.app:app"]
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env-non-dev

  db:
    container_name: avitotech_db
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env-non-dev
    restart: always